"""add_due_date_to_tasks

Revision ID: 1ee4d637b125
Revises: f698c7e82657
Create Date: 2025-12-24 14:10:15.883283

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ee4d637b125"
down_revision: Union[str, Sequence[str], None] = "f698c7e82657"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("due_date", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "due_date")
    # ### end Alembic commands ###
