"""initial migration

Revision ID: 90e8322eb776
Revises: 
Create Date: 2025-12-15 12:13:43.778294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90e8322eb776'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('git_contributions')
    op.drop_table('users')
    op.drop_table('projects')
    op.drop_table('tasks')
    op.drop_table('project_members')
    op.drop_table('system_logs')
    op.drop_table('clients')
    op.drop_table('logged_hours')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logged_hours',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('task_id', sa.INTEGER(), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('hours', sa.REAL(), nullable=False),
    sa.Column('note', sa.TEXT(), nullable=True),
    sa.Column('logged_at', sa.TEXT(), server_default=sa.text("(strftime('%Y-%m-%d %H:%M:%S', 'now'))"), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(strftime('%Y-%m-%d %H:%M:%S', 'now'))"), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_logs',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('level', sa.TEXT(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('meta', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(strftime('%Y-%m-%d %H:%M:%S', 'now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_members',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('role', sa.TEXT(), server_default=sa.text("'Member'"), nullable=False),
    sa.Column('added_at', sa.TEXT(), server_default=sa.text("(strftime('%Y-%m-%d %H:%M:%S', 'now'))"), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'To Do'"), nullable=False),
    sa.Column('assigned_to', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(strftime('%Y-%m-%d %H:%M:%S', 'now'))"), nullable=True),
    sa.Column('updated_at', sa.TEXT(), server_default=sa.text("(strftime('%Y-%m-%d %H:%M:%S', 'now'))"), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('client_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'Active'"), nullable=False),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(strftime('%Y-%m-%d %H:%M:%S', 'now'))"), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('username', sa.TEXT(), nullable=False),
    sa.Column('email', sa.TEXT(), nullable=False),
    sa.Column('password_hash', sa.TEXT(), nullable=False),
    sa.Column('display_name', sa.TEXT(), nullable=False),
    sa.Column('hourly_rate', sa.REAL(), server_default=sa.text('(0.00)'), nullable=True),
    sa.Column('created_at', sa.TEXT(), server_default=sa.text("(strftime('%Y-%m-%d %H:%M:%S', 'now'))"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('git_contributions',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('commit_hash', sa.TEXT(), nullable=False),
    sa.Column('commit_message', sa.TEXT(), nullable=True),
    sa.Column('branch', sa.TEXT(), nullable=True),
    sa.Column('committed_at', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('commit_hash')
    )
    # ### end Alembic commands ###
