"""Add work_sessions table and missing columns

Revision ID: 9e70db09a665
Revises: 907048ce1217
Create Date: 2026-01-06 20:28:28.201726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e70db09a665'
down_revision: Union[str, Sequence[str], None] = '907048ce1217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('last_resumed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', name='worksessionstatus'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_sessions_id'), ['id'], unique=False)

    with op.batch_alter_table('git_contributions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('committed_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_git_contributions_commit_hash'), ['commit_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_git_contributions_task_id'), ['task_id'], unique=False)
        batch_op.create_unique_constraint('uix_project_commit', ['project_id', 'commit_hash'])

    with op.batch_alter_table('logged_hours', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_logged_hours_date'))
        batch_op.drop_column('description')
        batch_op.drop_column('date')
        batch_op.drop_column('created_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('milestone_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f('ix_tasks_milestone_id'), ['milestone_id'], unique=False)
        batch_op.create_foreign_key('fk_tasks_milestone_id', 'milestones', ['milestone_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skills', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('skills')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_tasks_milestone_id'))
        batch_op.drop_column('due_date')
        batch_op.drop_column('milestone_id')

    with op.batch_alter_table('logged_hours', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.add_column(sa.Column('date', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.create_index(batch_op.f('ix_logged_hours_date'), ['date'], unique=False)

    with op.batch_alter_table('git_contributions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.drop_constraint('uix_project_commit', type_='unique')
        batch_op.drop_index(batch_op.f('ix_git_contributions_task_id'))
        batch_op.drop_index(batch_op.f('ix_git_contributions_commit_hash'))
        batch_op.alter_column('committed_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('work_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_sessions_id'))

    op.drop_table('work_sessions')
    # ### end Alembic commands ###
